apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "nextcloud.fullname" . }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      {{- $pullSecrets := concat (.Values.global.imagePullSecrets | default (list)) (.Values.imagePullSecrets | default (list)) | uniq }}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- range $pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: nextcloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/www/html
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
