{{- if and .Values.enabled .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-data
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- $sc := include "vaultwarden.storageClass" . }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
{{- end }}
