nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: gitea/gitea
  tag: "1.22.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

global:
  imagePullSecrets: []
  storageClass: ""
  hosts:
    gitea: ""
  commonLabels: {}

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  existingClaim: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: ""
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
