nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: "2.11.0"
  pullPolicy: IfNotPresent

global:
  storageClass: ""
  hosts:
    paperless: ""
    paperlessNgx: ""
  commonLabels: {}

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  data:
    enabled: true
    existingClaim: ""
    accessModes: ["ReadWriteOnce"]
    size: 10Gi
    storageClass: ""
    annotations: {}
  media:
    enabled: true
    existingClaim: ""
    accessModes: ["ReadWriteOnce"]
    size: 20Gi
    storageClass: ""
    annotations: {}
  consume:
    enabled: true
    existingClaim: ""
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
    storageClass: ""
    annotations: {}
  export:
    enabled: true
    existingClaim: ""
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
    storageClass: ""
    annotations: {}

podAnnotations: {}

backup:
  annotations: {}

resources: {}
