nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: memgraph/lab
  tag: "3.9.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

global:
  imagePullSecrets: []
  hosts:
    memgraphLab: ""
  commonLabels: {}

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  defaultHost: memgraph-lab.example.com
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

memgraph:
  host: platform-stack-memgraph
  port: 7687

podAnnotations: {}
podLabels: {}

env: []

podSecurityContext:
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

probes:
  readiness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 15

nodeSelector: {}
tolerations: []
affinity: {}
