#!/usr/bin/env bash
set -euo pipefail

warn() {
  echo >&2 "WARNING: $*"
}

HOME_DIR="${HOME:-/home/node/.openclaw/workspace-coder/.home}"
CODEX_HOME_DIR="${CODEX_HOME:-${HOME_DIR}/.codex}"
XDG_CONFIG_HOME_DIR="${XDG_CONFIG_HOME:-${HOME_DIR}/.config}"
XDG_CACHE_HOME_DIR="${XDG_CACHE_HOME:-${HOME_DIR}/.cache}"
XDG_STATE_HOME_DIR="${XDG_STATE_HOME:-${HOME_DIR}/.local/state}"
DOCKER_CONFIG_DIR="${DOCKER_CONFIG:-${HOME_DIR}/.docker}"
GIT_CONFIG_GLOBAL_FILE="${GIT_CONFIG_GLOBAL:-${HOME_DIR}/.gitconfig}"

CODER_GITEA_USERNAME="${CODER_GITEA_USERNAME:-coder}"
CODER_GITEA_EMAIL="${CODER_GITEA_EMAIL:-coder@example.invalid}"
CODER_GITEA_HOST="${CODER_GITEA_HOST:-}"
CODER_GITEA_BASE_URL="${CODER_GITEA_BASE_URL:-}"
CODER_GITEA_BOOTSTRAP_URL="${CODER_GITEA_BOOTSTRAP_URL:-${CODER_GITEA_BASE_URL}}"
CODER_GITEA_TEA_URL="${CODER_GITEA_TEA_URL:-}"
CODER_GITEA_PASSWORD="${CODER_GITEA_PASSWORD:-}"
CODER_GITEA_TOKEN="${CODER_GITEA_TOKEN:-}"
CODER_GITEA_TEA_LOGIN_NAME="${CODER_GITEA_TEA_LOGIN_NAME:-coder}"
CODER_GITEA_TEA_TOKEN_NAME="${CODER_GITEA_TEA_TOKEN_NAME:-openclaw-coder-sandbox}"

CODER_REGISTRY_HOST="${CODER_REGISTRY_HOST:-}"
CODER_REGISTRY_USERNAME="${CODER_REGISTRY_USERNAME:-}"
CODER_REGISTRY_PASSWORD="${CODER_REGISTRY_PASSWORD:-}"

export HOME="${HOME_DIR}"
export CODEX_HOME="${CODEX_HOME_DIR}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME_DIR}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME_DIR}"
export XDG_STATE_HOME="${XDG_STATE_HOME_DIR}"
export DOCKER_CONFIG="${DOCKER_CONFIG_DIR}"
export GIT_CONFIG_GLOBAL="${GIT_CONFIG_GLOBAL_FILE}"

tea_ssh_host() {
  if [ -n "${CODER_GITEA_HOST}" ]; then
    printf '%s\n' "${CODER_GITEA_HOST}"
    return
  fi

  local host="${CODER_GITEA_TEA_URL:-${CODER_GITEA_BASE_URL}}"
  host="${host#*://}"
  host="${host%%/*}"
  host="${host%%:*}"
  printf '%s\n' "${host}"
}

write_tea_config() {
  local ssh_host created_at
  ssh_host="$(tea_ssh_host)"
  created_at="$(date +%s)"

  cat > "${XDG_CONFIG_HOME}/tea/config.yml" <<EOF
logins:
- name: ${CODER_GITEA_TEA_LOGIN_NAME}
  url: ${CODER_GITEA_TEA_URL}
  token: ${CODER_GITEA_TOKEN}
  default: true
  ssh_host: ${ssh_host}
  ssh_key: ""
  insecure: false
  user: ${CODER_GITEA_USERNAME}
  created: ${created_at}
preferences:
  editor: false
  flag_defaults:
    remote: ""
EOF
  chmod 0600 "${XDG_CONFIG_HOME}/tea/config.yml"
}

write_docker_config() {
  local auth
  auth="$(printf '%s:%s' "${CODER_REGISTRY_USERNAME}" "${CODER_REGISTRY_PASSWORD}" | base64 | tr -d '\n')"

  jq -n \
    --arg host "${CODER_REGISTRY_HOST}" \
    --arg username "${CODER_REGISTRY_USERNAME}" \
    --arg password "${CODER_REGISTRY_PASSWORD}" \
    --arg auth "${auth}" \
    '{
      auths: {
        ($host): {
          username: $username,
          password: $password,
          auth: $auth,
        }
      }
    }' > "${DOCKER_CONFIG}/config.json"
  chmod 0600 "${DOCKER_CONFIG}/config.json"
}

mkdir -p \
  "${CODEX_HOME}" \
  "${XDG_CONFIG_HOME}/tea" \
  "${XDG_CACHE_HOME}" \
  "${XDG_STATE_HOME}" \
  "${DOCKER_CONFIG}"

CODEX_DEFAULT_MODEL="${CODEX_DEFAULT_MODEL:-gpt-5.4-mini}"

cat > "${CODEX_HOME}/config.toml" <<EOF
# Codex CLI configuration for ai-homebase coder agent
# Generated by coder-workspace-init.sh
#
# This deployment uses gpt-5.4-mini for cost efficiency, with selective
# override to gpt-5.3-codex for complex multi-file refactorings.
# The sandbox container is already Docker-isolated, so Codex itself runs
# without an extra inner sandbox or approval gate.
approval_policy = "never"
sandbox_mode = "danger-full-access"
model = "${CODEX_DEFAULT_MODEL}"
forced_login_method = "api"
EOF

if [ -n "${OPENAI_API_KEY:-}" ]; then
  jq -n --arg api_key "${OPENAI_API_KEY}" '{
    auth_mode: "apikey",
    OPENAI_API_KEY: $api_key,
  }' > "${CODEX_HOME}/auth.json"
  chmod 0600 "${CODEX_HOME}/auth.json"
else
  warn "OPENAI_API_KEY is unset; leaving coder workspace without seeded Codex auth"
fi

git config --global user.name "${CODER_GITEA_USERNAME}"
git config --global user.email "${CODER_GITEA_EMAIL}"

if [ -n "${CODER_GITEA_HOST}" ] && [ -n "${CODER_GITEA_PASSWORD}" ]; then
  cat > "${HOME}/.netrc" <<EOF
machine ${CODER_GITEA_HOST}
  login ${CODER_GITEA_USERNAME}
  password ${CODER_GITEA_PASSWORD}
EOF
  chmod 0600 "${HOME}/.netrc"
fi

if [ -z "${CODER_GITEA_BASE_URL}" ] && [ -n "${CODER_GITEA_HOST}" ]; then
  case "${CODER_GITEA_HOST}" in
    *.localtest.me) CODER_GITEA_BASE_URL="http://${CODER_GITEA_HOST}" ;;
    *) CODER_GITEA_BASE_URL="https://${CODER_GITEA_HOST}" ;;
  esac
fi

if [ -z "${CODER_GITEA_TEA_URL}" ]; then
  CODER_GITEA_TEA_URL="${CODER_GITEA_BASE_URL}"
fi

if [ -z "${CODER_GITEA_TOKEN}" ] && [ -n "${CODER_GITEA_BOOTSTRAP_URL}" ] && [ -n "${CODER_GITEA_USERNAME}" ] && [ -n "${CODER_GITEA_PASSWORD}" ]; then
  tokens_url="${CODER_GITEA_BOOTSTRAP_URL}/api/v1/users/${CODER_GITEA_USERNAME}/tokens"
  auth="${CODER_GITEA_USERNAME}:${CODER_GITEA_PASSWORD}"

  existing_token_ids="$(
    curl -fsS -u "${auth}" "${tokens_url}" \
      | jq -r --arg name "${CODER_GITEA_TEA_TOKEN_NAME}" '.[] | select(.name == $name) | .id' \
      || true
  )"
  if [ -n "${existing_token_ids}" ]; then
    for token_id in ${existing_token_ids}; do
      curl -fsS -X DELETE -u "${auth}" "${tokens_url}/${token_id}" >/dev/null || true
    done
  fi

  CODER_GITEA_TOKEN="$(
    curl -fsS -u "${auth}" \
      -H 'Content-Type: application/json' \
      -d "{\"name\":\"${CODER_GITEA_TEA_TOKEN_NAME}\",\"scopes\":[\"all\"]}" \
      "${tokens_url}" 2>/dev/null \
      | jq -r '.sha1 // empty' \
      || true
  )"
fi

if [ -n "${CODER_GITEA_TEA_URL}" ] && [ -n "${CODER_GITEA_TOKEN}" ]; then
  write_tea_config
else
  warn "coder Gitea token is unavailable; leaving coder workspace without seeded tea login"
fi

if [ -n "${CODER_REGISTRY_HOST}" ] && [ -n "${CODER_REGISTRY_USERNAME}" ] && [ -n "${CODER_REGISTRY_PASSWORD}" ]; then
  write_docker_config
else
  warn "coder registry credentials are unavailable; leaving coder workspace without registry auth"
fi
