{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- $sc := include "paperless-ngx.storageClass" (list .Values.persistence.data .) }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
---
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.media.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- $sc := include "paperless-ngx.storageClass" (list .Values.persistence.media .) }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
{{- end }}
