{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "paperless-ngx.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paperless-ngx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paperless-ngx.selectorLabels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.backup.annotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.backup.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: paperless-ngx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.secretRefs }}
          env:
            {{- range .Values.secretRefs }}
            - name: {{ .envVar }}
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
          {{- end }}
          {{- if .Values.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: /usr/src/paperless/data
            {{- end }}
            {{- if .Values.persistence.media.enabled }}
            - name: media
              mountPath: /usr/src/paperless/media
            {{- end }}
            {{- if .Values.persistence.consume.enabled }}
            - name: consume
              mountPath: /usr/src/paperless/consume
            {{- end }}
            {{- if .Values.persistence.export.enabled }}
            - name: export
              mountPath: /usr/src/paperless/export
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if and .Values.persistence.data.enabled .Values.persistence.data.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
        {{- end }}
        {{- if and .Values.persistence.media.enabled .Values.persistence.media.existingClaim }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.media.existingClaim }}
        {{- end }}
        {{- if and .Values.persistence.consume.enabled .Values.persistence.consume.existingClaim }}
        - name: consume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.consume.existingClaim }}
        {{- end }}
        {{- if and .Values.persistence.export.enabled .Values.persistence.export.existingClaim }}
        - name: export
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.export.existingClaim }}
        {{- end }}
{{- end }}
