apiVersion: v1
kind: Service
metadata:
  name: {{ include "shared-redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "shared-redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
  selector:
    app.kubernetes.io/name: {{ include "shared-redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
